export enum BlockType {
  Section = 'section',
  Actions = 'actions',
  Context = 'context',
  Input = 'input',
  File = 'file',
  Divider = 'divider',
  Image = 'image',
  Header = 'header',
  Video = 'video',
  RichText = 'rich_text',
  Markdown = 'markdown',
  Table = 'table',
  ContextActions = 'context_actions',
}
